default:
  image: glyhood/ci-image:latest
  tags:
    - ekscluster

variables:
  helm_registry_name: budpay-helm-registry

stages:
  - test
  - release

.helm_registry_login: &helm_registry_login
  - helm plugin install https://github.com/chartmuseum/helm-push
  - helm repo add --username ${GIT_USER} --password ${GIT_TOKEN} budpay-helm-registry https://gitlab.com/api/v4/projects/46031901/packages/helm/stable

release_dev:
  stage: release
#  only: [tags]
  script:
    - *helm_registry_login
    - PACKAGE=`helm package dev-charts | cut -d ":" -f 2`
    - helm cm-push ${PACKAGE} ${helm_registry_name}
  only:
    changes:
      - /dev-charts/*

release_prod:
  stage: release
#  only: [tags]
  script:
    - *helm_registry_login
    - PACKAGE=`helm package prod-charts | cut -d ":" -f 2`
    - helm cm-push ${PACKAGE} ${helm_registry_name}
  only:
    changes:
      - /prod-charts/*



